#SPDX-License-Identifier: MIT-0
---
# tasks file for kubectl


- name: Download kubectl
  get_url:
    url: https://dl.k8s.io/release/v1.32.0/bin/linux/amd64/kubectl
    dest: /usr/local/bin/kubectl
    mode: '0755'

- name: Verify kubectl installation
  command: kubectl version --client
  register: kubectl_output

- debug:
    var: kubectl_output.stdout
