name: Code Quality

on:
  push:
    branches: [main]

jobs:

  golangci:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.26'

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          working-directory: backend
          version: latest
