name: DevSecOps End to End Pipeline

on:
    push:
        branches: [main]

jobs:
    
    # CI with integration and security scanning
    
    secrets-scan:
        uses: ./.github/workflows/secrets-scan.yml    

    docker-scan:
        uses: ./.github/workflows/docker-lint.yml    
    
    # build once the security sacn are complete
    build:
        needs: [secrets-scan,docker-scan]
        uses: ./.github/workflows/ci.yml 
        secrets: inherit
    
    trivy:
        needs: [build]
        uses: ./.github/workflows/image-scan.yml  
        secrets: inherit  
        
    # Deploy to production  
    
     
    deploy:
        needs: [trivy]
        uses: ./.github/workflows/cd.yml
        secrets: inheriti
